language: php

compiler:
  - gcc
  - clang

os:
  - linux

services:
  - docker

php:
  - 7.1-nts
  - 7.2-nts
  - 7.3-nts
  - 7.4-nts
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

notifications:
  email: yanlong.hee@gmail.com

sudo: required

# compile
before_script:
  - date
  - env
  - uname -a
  - ulimit -a
  - php -v
  - ls -al
  - pwd
  - echo "`git log -20 --pretty --oneline`"
  - echo "`git log -10 --stat --pretty --oneline`"
  - ./travis/simple-compile.sh
  - php --ri skywalking

script:
  - ./travis/route.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
