name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.0', '7.1', '7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: skywalking-php

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: curl, json
    - name: Install library
      run: sudo apt-get update && sudo apt-get install -y curl libcurl4-openssl-dev
    
    - name: Configure and make
      run: cd skywalking-php && phpize && ./configure && make && sudo make install && cd ..
      
    - name: Checkout agent test tool
      uses: actions/checkout@v2
      with:
        repository: apache/skywalking-agent-test-tool
        path: skywalking-agent-test-tool
    
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: aahmed-se/setup-maven@v3
      with:
        maven-version: 3.6.1
    
    - name: 'Start apache SkyWalking mock collector'
      run: |
        cd skywalking-agent-test-tool
        mvn package -DskipTests
        tar zxvf ./dist/skywalking-mock-collector.tar.gz -C ./mock-collector
        ls
        ls mock-collector
        ls mock-collector/bin
        ls mock-collector/skywalking-mock-collector
        nohup sudo bash -c './mock-collector/bin/collector-startup.sh' &
        cat nohup.out
        cd ..
      
    - name: Check mock collector
      run: curl http://localhost:12800/status
      
